=== msshin0313/daniel-code-snippet/trunk/javademo/JAXP/DOMAIN.XSD
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="name" type="xs:string"/>
    <xs:element name="desc" type="xs:string"/>
    <xs:element name="pic_url" type="xs:string"/>

    <xs:group name="domainbasic">
        <xs:element ref="name"/>
        <xs:element ref="desc"/>
        <xs:element ref="pic_url" minOccurs="0" maxOccurs="1"/>
    </xs:group>

    <xs:simpleType name="taste">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Vegetarian"/>
            <xs:enumeration value="Seafood"/>
            <xs:enumeration value="Sweet"/>
            <xs:enumeration value="Spicy"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="season">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Spring"/>
            <xs:enumeration value="Summer"/>
            <xs:enumeration value="Autumn"/>
            <xs:enumeration value="Winter"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Sacred Mountain"/>
            <xs:enumeration value="Snow Mountain"/>
            <xs:enumeration value="Massif"/>
            <xs:enumeration value="Natural Mountain"/>
            <xs:enumeration value="Sea"/>
            <xs:enumeration value="River"/>
            <xs:enumeration value="Lake"/>
            <xs:enumeration value="Waterfall"/>
            <xs:enumeration value="Fount"/>
            <xs:enumeration value="Temple"/>
            <xs:enumeration value="Museum"/>
            <xs:enumeration value="Famous Residence"/>
            <xs:enumeration value="Tomb"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="food">
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="domainbasic"/>
            </xs:sequence>
            <xs:attribute name="taste" type="taste" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="resort">
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="domainbasic"/>
                <xs:element ref="food" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="type" type="type" use="required"/>
            <xs:attribute name="season" type="season" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="domainmodel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="resort" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== msshin0313/daniel-code-snippet/tags/20110614/java/+demo/JAXP/DomainModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<domainmodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="domain.xsd">

    <resort type="Sacred Mountain" season="Spring">
        <name>Mount. Tai</name>
        <desc>Located in Shandong, one of the so-called '5 mount'</desc>
        <pic_url>pic/taishan.jpg</pic_url>
        <food taste="Sweet">
            <name>Youtiao</name>
            <desc>Very long and crispy</desc>
        </food>
    </resort>

</domainmodel>
